### ISSUE TITLE
attrs.xml file shows error 

### ISSUE THREAD

**Issue by HemangNirmal** [Todd-Davies/ProgressWheel#21]
I have copy down the code in guidence in file named attrs.xml file but it shows error 

so please tell me how to make attrs.xml file.

<?xml version="1.0" encoding="utf-8"?>

<declare-styleable name="ProgressWheel">   
<attr name="text" format="string" />   
<attr name="textColor" format="color" />   
<attr name="textSize" format="dimension" />   
<attr name="barColor" format="color" />   
<attr name="rimColor" format="color" />   
<attr name="rimWidth" format="dimension" />   
<attr name="spinSpeed" format="integer" />     
<attr name="circleColor" format="color" />     
<attr name="radius" format="dimension" />   
<attr name="barWidth" format="dimension" />   
<attr name="barLength" format="dimension" />   
</declare-styleable>

**Comment by hasitpbhatt** [comment]
Please check sample attrs.xml https://developer.android.com/samples/BasicSyncAdapter/res/values/attrs.html
