### ISSUE TITLE
Linearlayout weight

### ISSUE THREAD

**Issue by trant** [Todd-Davies/ProgressWheel#23]
The ProgressWheel control is only drawn when I specify height and width. If I use a linear layout, and then specify layout_weight=1 and layout_width=0dp, It is not displayed.

Example of xml : https://www.dropbox.com/s/xmxp36rbarllz5d/f.xml

**Comment by skjolber** [comment]
This is because the onMeasure method really does no checking on whether width or height is unspecified.

**Comment by skjolber** [comment]
The fix has been merged, please verify it.
