### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by jitpack-io** [Todd-Davies/ProgressWheel#49]
Would be great to have a [GitHub Release](https://github.com/Todd-Davies/ProgressWheel/releases) of ProgressWheel

**Comment by Todd-Davies** [comment]
Here you are: https://github.com/Todd-Davies/ProgressWheel/releases/tag/1.0

**Comment by jitpack-io** [comment]
Brilliant! Now it's easier to get it as a Gradle/Maven dependency:
https://jitpack.io/#Todd-Davies/ProgressWheel/1.0
