### ISSUE TITLE
How to set maximum value for the progress bar?

### ISSUE THREAD

**Issue by sadarshannaiynar** [Todd-Davies/ProgressWheel#55]
Hey Todd, 

First off, this is an amazing library. But i can't figure out how to set the maximum value for the progress bar.

**Comment by fbis251** [comment]
Hey, on the README there's a section with this information on it:

    Incrementing the progress wheel is slightly more tricky, you call .incrementProgress().
    However, this is out of 360, (because a circle has 360 degrees), and will automatically
    reset once you get past 360. A percentage display is automatically displayed.
