### ISSUE TITLE
Gradle dependency causes AndroidManifest errors

### ISSUE THREAD

**Issue by sureshjoshi** [Todd-Davies/ProgressWheel#56]
After I install this dependency, I'm getting some AndroidManifest issues (Android 1.2.2 - Gradle tools 1.2.3).

Error:(11, 9) Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:11:9
Error:(13, 9) Attribute application@theme value=(@style/AppTheme) from AndroidManifest.xml:13:9
	is also present at com.github.Todd-Davies:ProgressWheel:1.0:14:9 value=(@android:style/Theme.NoTitleBar)
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:8:5 to override

**Comment by sureshjoshi** [comment]
Also, I think this is fixed by putting:
        tools:replace="android:theme, android:icon"

as the first line in the application tag in AndroidManifest, however, a dependency shouldn't cause manifest problems - might need to replace the progress wheel manifest

**Comment by nayram** [comment]
Hi I have the same issue and tools:replace="android:theme, android:icon" in the application of of the manifest didn't help.

**Comment by contervis** [comment]
Added tools:replace="android:theme,android:icon" in the application tag of my AndroidManifest, but this cause the app ic_launcher icon to be the one of the library.

**Comment by Frildoren** [comment]
Same issue here :(

**Comment by OmarAliSaid** [comment]
same goes here

**Comment by morganlutz** [comment]
Same issue here.

**Comment by MrOutis** [comment]
Same here :disappointed:

**Comment by evansmj** [comment]
Same here...

**Comment by petrorington** [comment]
@Todd-Davies I'm experiencing same issue. Can you please let me know if you have got a solution?
