### ISSUE TITLE
ERROR: Failed to resolve: ProgressWheel 1.2

### ISSUE THREAD

**Issue by AkioAlex0817** [Todd-Davies/ProgressWheel#70]
Hi. Nice to meet you. I am Akio
Please tell me, how can I fix this issue.
And I have added in gradle : 
repositories {
    maven { url "https://jitpack.io" }
}
Thanks.

**Comment by khushal123** [comment]
I am having the same issue  : ERROR: Failed to resolve: com.github.Todd-Davies:ProgressWheel:1.2
I have added in gradle:  maven { url "https://jitpack.io" }

**Comment by munhozneto** [comment]
I'm having the same problem. My project has been using this library for years, but I use automated builds with CI and it always has to download the dependencies of the project.

**Comment by k4rm3l0** [comment]
In https://jitpack.io/#Todd-Davies/ProgressWheel/ i see a build failure on release 1.2

**Comment by choyisus** [comment]
This  https://jitpack.io/#Todd-Davies/ProgressWheel/ V 1.2 is out of site

**Comment by mobiledeveloper90** [comment]
How can we resolve it ?

**Comment by fenggit** [comment]
me too 

ERROR: Failed to resolve: ProgressWheel

**Comment by AkioAlex0817** [comment]
Hi. Developers. I fixed this issue.
If you need ask, contact with me.
My via email is akioalex0817@gmail.com
Thank you

**Comment by AkioAlex0817** [comment]
> How can we resolve it ?

Contact with me. via Email: akioalex0817@gmail.com
I can help you

**Comment by AkioAlex0817** [comment]
I am already fix this issue

**Comment by martirius** [comment]
@AkioAlex0817 post the solution here, so everyone can read without contacting you personally.

**Comment by mohsen202** [comment]
hi
i have a same problem 
please help me

**Comment by AkioAlex0817** [comment]
Check your gmail.
Thank you

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by munhozneto** [comment]
I solved this problem by cloning the project and then added it as an Android library in my project.

**Comment by AkioAlex0817** [comment]
That's sound great. Good Luck.

Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by k4rm3l0** [comment]
AkioAlex0817 can you sand me the solution?
Thank you.

**Comment by AkioAlex0817** [comment]
You must make this file: under res/value/attrs.xml.
And add code follow URL.
https://github.com/Todd-Davies/ProgressWheel/blob/master/res/values/attrs.xml
And You must make file anywhere. And filename is ProgressWheel and class name ProgressWheel.
And add code follow URL
https://github.com/Todd-Davies/ProgressWheel/blob/master/src/com/todddavies/components/progressbar/ProgressWheel.java

And Remove  implementation 'com.github.Todd-Davies:ProgressWheel:1.2' from gradle.
It will help you.
Thank you.


Sent from Outlook<http://aka.ms/weboutlook>
________________________________
